src/Entity/File.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\FileRepository")
 */
class File
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="files")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;
     /**
     * @ORM\ManyToOne(targetEntity="App\Entity\SettingFile", inversedBy="files", cascade={"all"}, fetch="EAGER")
     * @ORM\JoinColumn(nullable=false)
     */
    private $setting_file;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $path;
    /**
     * @ORM\Column(type="string", length=255)
     */
 
    private $date_created;

    /**
     * @ORM\Column(type="boolean")
     */
    private $archived;
     
    /**
     * @ORM\Column(type="boolean")
     */
    private $converted;

    public function __construct($current_user,$path)
    {
        $this->user = $current_user;
        $this->path= $path;
        $this->archived= false;
        $this->converted= false;
        // $this->date_create= new \DateTime('now');
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getPath(): ?string
    {
        return $this->path;
    }

    public function setPath(string $path): self
    {
        $this->path = $path;

        return $this;
    }

    public function getDateCreated()
    {
        return $this->date_created;
    }

    public function setDateCreated($date_created): self
    {
        $this->date_created = $date_created;

        return $this;
    }

    public function getArchived(): ?bool
    {
        return $this->archived;
    }

    public function setArchived(bool $archived): self
    {
        $this->archived = $archived;

        return $this;
    }

    public function getParentFile(): ?string
    {
        return $this->parent_file;
    }

    public function setParentFile(string $parent_file): self
    {
        $this->parent_file = $parent_file;

        return $this;
    }

    public function getConverted(): ?bool
    {
        return $this->converted;
    }

    public function setConverted(bool $converted): self
    {
        $this->converted = $converted;

        return $this;
    }

    public function getSettingFile(): ?SettingFile
    {
        return $this->setting_file;
    }

    public function setSettingFile(?SettingFile $setting_file): self
    {
        $this->setting_file = $setting_file;

        return $this;
    }

 
}

src/Controller/FileController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\User\UserInterface;

class FileController extends AbstractController
{
    /**
     * @Route("/file", name="file")
     */
    public function index()
    {
        return $this->render('file/index.html.twig', [
            'controller_name' => 'FileController',
        ]);
    }
     /**
     * @Route("/file/my-files", name="my_files")
     */
    public function myFiles(UserInterface $current_user)
     {
        $files=$current_user->getFiles();
        $setting_files=array();
        foreach ($files as $value) {
            if(!in_array($value->getSettingFile(),$setting_files))
                $setting_files[] = $value->getSettingFile();
        }
        return $this->render('file/my_files.html.twig', [
            'files' => $current_user->getFiles(), 'setting_files' => $setting_files
        ]);
    }
}

templates/file/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello FileController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>
{{dump(app)}}

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ '/home/ezequiel/Prebi/dspace2ojs_symfony/src/Controller/FileController.php'|file_link(0) }}">src/Controller/FileController.php</a></code></li>
        <li>Your template at <code><a href="{{ '/home/ezequiel/Prebi/dspace2ojs_symfony/templates/file/index.html.twig'|file_link(0) }}">templates/file/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

templates/file/my_files.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello FileController!
{% endblock %}

{% block body %}
    {% for setting in setting_files %}
        <div class="wrapper container">
            <div class="button_table">
                <button class="process_files    {{setting.parentFile}}">
                    Process all
                </button>
                <button class="archived_files    {{setting.parentFile}}">
                    Archived all
                </button>
            </div>

            <table class="table table-striped">
                <thead>
                    <tr>
                        <th scope="col">
                            <strong>{{setting.parentFile}}</strong>
                        </th>
                        <th scope="col">Xml</th>
                        <th scope="col">Csv</th>
                        <th scope="col">Process</th>
                        <th scope="col">Archived</th>
                    </tr>
                </thead>
                <tbody>
                    {% for file in setting.files %}
                        {% if not file.archived %}
                            {% set path = file.path | split('/') | last | split('.') | first %}
                            <tr id="tr_{{path}}">
                                <th scope="row">{{loop.index}}</th>
                                <td>
                                    <a href="{{ asset(file.path) }}">{{ asset(file.path) | split('/') | last }}
                                    </a>
                                </td>
                                <td id="{{path}}">
                                    {% if  file.converted %}
                                        <a href="{{ asset(file.path) ~ '.xml' }}">{{ asset(file.path) | split('/') | last ~ '.xml'}}
                                        </a>
                                    </td>
                                {% else %}
                                    -
                                {% endif %}
                                <td>
                                    {% if not file.converted %}
                                        <button class="process_file parent_{{setting.parentFile}}" value="{{file.path}}" id_td="{{ asset(file.path) | split('/') | last | split('.') | first}}">Process</button>
                                    {% endif %}
                                </td>
                                <td>
                                    <button class="archived_file parent_{{setting.parentFile}}" value="{{file.path}}" id_td="{{ asset(file.path) | split('/') | last | split('.') | first}}">Archived</button>
                                </td>
                            </tr>
                        {% endif %}
                    {% endfor %}
                </tbody>
            </table>
            <hr>
        </div>
    {% endfor %}
{% endblock %}
{% block javascripts %}
    {{ parent() }}
    <script src="{{ asset('js/process_ajax.js') }}" > </script>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>


{% endblock %}